Repository acm-ucr/hsa-website, pull requests merged in 2025-02, with the labels that each got.

#50 Magui203/404 page
  public/assets/hsa8.svg
  public/assets/hsa9.svg
  src/app/not-found.tsx
Labels: Ready for Review

#62 Song Myung (real)
  src/app/layout.tsx
Labels: bug, Ready for Review

#40 Board Member Component
  public/assets/boardMember1.webp
  public/assets/boardMember2.webp
  public/assets/boardMember3.webp
  public/assets/boardMember4.webp
  public/assets/boardMember5.webp
  public/assets/toasty.webp
  src/app/board/page.tsx
  src/components/board/Board.tsx
  src/components/example.tsx
Labels: Ready for Review, board

#58 Added Nav Bar Hover attributes. Created underline when elements in na…
  src/components/Navigation.tsx
Labels: Ready for Review, address comments

#55 Made the footer
  public/assets/footerImg.png
  public/assets/tree.svg
  src/components/Footer.tsx
Labels: address comments

#72 Added images to about us section
  public/hsaPeople.webp
  src/components/home/About.tsx
Labels: Ready for Review

#71 fixed the navigation bar issues
  src/components/Navigation.tsx
Labels: Ready for Review

#78 Fixes to Mission and Do Section
  src/components/home/Do.tsx
  src/components/home/Mission.tsx
Labels: Ready for Review

#82 fixed event mobile response
  src/components/events/EventCardBase.tsx
Labels: Ready for Review, events, mobile responsiveness

#73 merge about text with about image
  src/components/home/About.tsx
Labels: address comments

#88 added link to join us button
  src/components/home/JoinButton.tsx
Labels: Ready for Review, home

#79 Hero Image Done
  src/components/home/Hero.tsx
  src/components/home/HeroCard.tsx
Labels: Ready for Review

#89 Fixed Header Fonts
  src/components/Header.tsx
Labels: Ready for Review

#81 Converted HSA logo image from png to ico and replaced the favicon fi…
  src/app/HSA Logo.ico
  src/app/favicon.ico
Labels: address comments

#95 Turns board components into map
  public/assets/AnjalyThao.webp
  public/assets/JacobVang.webp
  public/assets/KayleighYoung.webp
  public/assets/LincolnYang.webp
  public/assets/SaraCha.webp
  src/app/board/page.tsx
  src/components/board/Board.tsx
  src/components/board/Boards.tsx
  src/data/Board.js
Labels: Ready for Review

#90 Fixed navigation Bar
  src/components/Navigation.tsx
  src/components/home/About.tsx
  src/data/NavBarData.ts
Labels: address comments

#107 Added Mobile Responsiveness to What We Do Section
  src/components/home/Do.tsx
Labels: Ready for Review

#115 Added Hover Design to Join Us Button
  src/components/home/JoinButton.tsx
Labels: Ready for Review

#113 nav bar recentered right
  src/components/Navigation.tsx
  src/data/NavBarData.ts
Labels: Ready for Review

#106 Adds mobile response to board
  src/components/Header.tsx
  src/components/board/Board.tsx
  src/components/board/Boards.tsx
  src/data/Board.js
Labels: address comments, mobile responsiveness

#112 Tanishqmano/404 mobile
  src/app/not-found.tsx
Labels: Ready for Review, mobile responsiveness

#127 Fixed footer/border image to make it smaller.
  public/assets/border.svg
  src/components/Footer.tsx
Labels: Ready for Review
