Repository acm-ucr/hsa-website, pull requests merged in 2025-03, with the labels that each got.

#129 board animation
  src/components/board/Board.tsx
Labels: Ready for Review, board, animation

#131 Upcoming Event Cards (Calendar)
  src/app/calendar/page.tsx
  src/components/calendar/EventCard.tsx
  src/data/EventCardData.ts
Labels: Ready for Review, calendar

#111 moved components and fixed for mobile responsiveness
  src/components/home/About.tsx
Labels: Ready for Review

#132 Animate header
  src/components/Header.tsx
Labels: address comments

#137 Added Animations to Event Card
  src/components/events/EventCardBase.tsx
Labels: Ready for Review

#136 Maguilar05/mission mobile resp
  package-lock.json
  package.json
  src/app/HSA Logo.ico
  src/components/home/JoinButton.tsx
  src/components/home/Mission.tsx
Labels: Ready for Review, address comments, mobile responsiveness

#138 Code quality: prop interfaces
  src/components/Header.tsx
  src/components/board/Board.tsx
  src/components/events/EventCardBase.tsx
  src/components/gallery/Photos.tsx
Labels: Ready for Review

#151 Calendar fixes + EventCard Gcal integration
  src/app/calendar/page.tsx
  src/components/calendar/CalendarEvents.tsx
  src/components/calendar/EventCard.tsx
  src/components/ui/calendar.tsx
Labels: Ready for Review, calendar

#150 footer mobile DONE
  src/components/Border.tsx
  src/components/Footer.tsx
Labels: Ready for Review, home, mobile responsiveness

#153 fixed join us button
  src/components/home/Hero.tsx
  src/components/home/JoinButton.tsx
Labels: Ready for Review, home

#159 fix gap for board
  src/components/board/Boards.tsx
Labels: Ready for Review

#160 Fix Event Card Bug + Calendar Today Styling
  src/components/calendar/CalendarEvents.tsx
  src/components/calendar/EventCard.tsx
  src/components/ui/calendar.tsx
Labels: Ready for Review

#114 Made the text responsive
  src/components/home/Hero.tsx
  src/components/home/HeroCard.tsx
Labels: address comments

#162 Finally made changes
  src/components/home/Do.tsx
  src/components/home/Mission.tsx
Labels: Ready for Review, animation

#154 Fixed Event Card
  src/components/events/EventCardBase.tsx
Labels: Ready for Review, mobile responsiveness, animation

#168 added animation
  src/components/home/Mission.tsx
Labels: Ready for Review, animation

#142 Added animations for About Us
  package-lock.json
  src/components/home/About.tsx
Labels: Ready for Review, animation

#172 Add cool animations to bars on home
  src/components/home/About.tsx
  src/components/home/Hero.tsx
  src/components/home/Mission.tsx
Labels: enhancement, Ready for Review
