Repository acm-ucr/hsa-website, pull requests merged in 2025-01, with the labels that each got.

#15 change the Hero name
  src/components/home/Hero.tsx
Labels: Ready for Review

#20 Brianubyun/navbar
  public/hsaImage.webp
  src/components/Navigation.tsx
Labels: Ready for Review

#29 Added fonts into config
  tailwind.config.ts
Labels: Ready for Review

#32 Finished Mission Text Section
  src/components/home/Mission.tsx
Labels: Ready for Review

#42 Fix custom fonts
  CNAME
  src/app/layout.tsx
  tailwind.config.ts
Labels: bug, Ready for Review

#35 Add events component
  src/app/events/page.tsx
  src/components/events/Banquet.tsx
  src/components/events/EventCardBase.tsx
  src/components/events/Friendship-games.tsx
  src/components/events/HmongNewYear.tsx
Labels: Ready for Review

#25 Daniyal/title file
  src/app/board/page.tsx
  src/app/calendar/page.tsx
  src/app/events/page.tsx
  src/app/gallery/page.tsx
  src/app/page.tsx
  src/components/Header.tsx
Labels: address comments

#39 Ariklee2/hero
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/HeroCard.tsx
  src/components/JoinButton.tsx
  src/components/YellowBar.tsx
  src/components/example.tsx
  src/components/home/Hero.tsx
  tsconfig.json
Labels: Ready for Review

#46 Tanishqmano/what we do section
  src/app/page.tsx
  src/components/example.tsx
  src/components/home/Do.tsx
  src/components/home/Hero.tsx
  src/components/home/Mission.tsx
  src/components/home/YellowBar.tsx
Labels: Ready for Review
